vagrantfile-local:
  vm:
    box: 'puppetlabs/centos-6.6-64-puppet'
    hostname: drupaldev
    domain: 'local'
    memory: 1024
    network:
      private_network: 192.168.33.10
      forwarded_port:
        http:
          host: 8081
          guest: 80
        https:
          host: 4297
          guest: 443